### PR TITLE
Disabled image context menu on hand cards for mobile

### PR DESCRIPTION
**Pull request by Lykae**
Found the perpetrator.

### CODE REVIEW

**Comment by LaustinSpayce** [comment]
Pulled changes and did a quick test, the Right Column component is covering the entire game board meaning you can't click any items etc:

Screenshot 2023-09-22 at 9 12 11 PM

**Comment by Lykae** [comment]
After cleaning my glasses I can now see the overlay as well. I removed it.

**Comment by Lykae** [comment]
NVM I removed for desktop as well.

**Comment by PvtVoid** [comment]
Hey, I will close this since it's inactive for a year. @Lykae, please let me know if you want to keep working on this. I hope I can help you move forward with the idea if interested :)

**Pull request closed without merging**
